version: '3.4'

services:
  ms.sql.users.db:
    image: mcr.microsoft.com/mssql/server

  ms.sql.jobseekers.db:
    image: mcr.microsoft.com/mssql/server

  ms.users.api:
    image: ${DOCKER_REGISTRY-}msusers
    build:
      context: .
      dockerfile: ms.users/ms.users.api/Dockerfile

  ms.jobseekers.api:
    image: ${DOCKER_REGISTRY-}msjobseekers
    build:
      context: .
      dockerfile: ms.jobseekers/ms.jobseekers.api/Dockerfile

  ms.spa:
    image: ${DOCKER_REGISTRY-}msspa
    build: 
        context: .
        dockerfile: ms.spa/Dockerfile
    
  ms.web:
    image: ${DOCKER_REGISTRY-}msweb
    build: 
        context: .
        dockerfile: ms.web/ms.web.ui/Dockerfile