version: '3.4'

services:
  ms.sql.users.db:
    container_name: ms.sql.users.db
    restart: always
    volumes:
      - /c/data/docker/careertrackpro/sqlserver/users:/var/opt/mssql/data
    ports:
      - "1417:1433"
    environment:
      SA_PASSWORD: ".123Pass456."
      ACCEPT_EULA: "Y"

  ms.sql.jobseekers.db:
    container_name: ms.sql.jobseekers.db
    restart: always
    volumes:
      - /c/data/docker/careertrackpro/sqlserver/jobseekers:/var/opt/mssql/data
    ports:
      - "1418:1433"
    environment:
      SA_PASSWORD: ".123Pass456."
      ACCEPT_EULA: "Y"

  ms.sql.jobapplications.db:
    container_name: ms.sql.jobapplications.db
    restart: always
    volumes:
      - /c/data/docker/careertrackpro/sqlserver/jobapplications:/var/opt/mssql/data
    ports:
      - "1419:1433"
    environment:
      SA_PASSWORD: ".123Pass456."
      ACCEPT_EULA: "Y"

  ms.users.api:
    container_name: ms.users.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:UserDB:HostName=ms.sql.users.db"
      - "ConnectionStrings:UserDB:Catalogue=Users"
      - "ConnectionStrings:UserDB:User=sa"
      - "ConnectionStrings:UserDB:Password=.123Pass456."
    ports:
      - "9010:80"
    depends_on:
      - ms.sql.users.db

  ms.jobseekers.api:
    container_name: ms.jobseekers.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:StudentDB:HostName=ms.sql.jobseekers.db"
      - "ConnectionStrings:StudentDB:Catalogue=JobSeekers"
      - "ConnectionStrings:StudentDB:User=sa"
      - "ConnectionStrings:StudentDB:Password=.123Pass456."
    ports:
      - "9020:80"
    depends_on:
      - ms.sql.jobseekers.db

  ms.jobapplications.api:
    container_name: ms.jobapplications.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:StudentDB:HostName=ms.sql.jobapplications.db"
      - "ConnectionStrings:StudentDB:Catalogue=JobApplications"
      - "ConnectionStrings:StudentDB:User=sa"
      - "ConnectionStrings:StudentDB:Password=.123Pass456."
    ports:
      - "9030:80"
    depends_on:
      - ms.sql.jobapplications.db

  ms.spa:
    container_name: ms.spa
    ports:
      - "4200:80"
    depends_on:
      - ms.users.api

  ms.web:
    container_name: ms.web
    ports:
      - "4300:8080"
    depends_on:
      - ms.users.api